#!/bin/bash

curl -su `jira me`:$JIRA_API_TOKEN \
	'https://nerdsandcompany.atlassian.net/wiki/api/v2/pages/2313093121?body-format=atlas_doc_format' | \
	jq -r '.body | .atlas_doc_format | .value | fromjson | .content[] | select(.type == "taskList") | .content[] 
	| select(.attrs.state = "TODO") | .content[] | .text'
