#!/bin/bash

set -e

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
(echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> /Users/ammar/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"
brew tap heroku/brew && brew install heroku
brew tap ankitpokhrel/jira-cli

brew install --cask slack microsoft-edge ubersicht 1password 1password-cli

brew install \
	docker \
	imagemagick \
	hub \
	direnv \
	gnu-tar \
	gpg \
	jq \
	fzf \
	libpq \
	gcalcli \
	lazygit \
	lazydocker \
	jira-cli \
	gh \
	rg \
	nnn \
	asdf \
	fish \
	lua-language-server \
	koekeishiya/formulae/skhd \
	koekeishiya/formulae/yabai \
	wallpaper \
	alacritty \
	ripgrep \
	libpq \
	fd \
	calcurse

skhd --start-service
yabai --start-service
/opt/homebrew/opt/fzf/install
sudo sh -c 'echo /opt/homebrew/bin/fish >> /etc/shells'
chsh -s /opt/homebrew/bin/fish


cp ~/secrets ~/.secrets
