#!/bin/bash

set -e

. params
. `dirname $0`/simpl/vars

FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS --ansi --height=50% --select-1"
start_date=`date_picker --query $date`
start_date=${start_date% *}
end_date=$start_date


hours=`curl -s -G -H "$auth_key_header" -H "$auth_secret_header" "$base_url""timers/timer" \
	-d "sort=start_date" \
	-d "q[employee.id]=$employee_id" `

		echo $hours
		exit
total=`jq '[.[] | .hours] | add' <<< $hours | bc -l \
	| awk -F. ' { print sprintf("%02d:%02d", $1, substr($2, 0, 2) * .6) }'`

delete_command="`dirname $0`/simpl/delete_entry"
jq -r '.[] |.date + " " + .start + " to " + .end + " " + .project + " " + .service + " " + .type + " " +
.note + " " + .id' <<< $hours \
	| fzf --with-nth=1..-2 \
	--bind="ctrl-d:execute($delete_command {-1})+become(get_time --date $date)" \
	--header "total: $total; CTRL+D to delete; CTRL+N for forward; CTRL+P for backward; CTRL+W to toggle week"

