#!/bin/bash
app_json=`pathfinder . app.json`

query=""
if [ ! -z $app_json ]
then
	query=`jq -r '.name' $app_json`
fi

(heroku whoami || heroku login) > /dev/null &&
	heroku apps --all | tail -n+2 | fzf --select-1 --query "$query$1" | awk '{print $1}'
