#!/bin/bash

set -e

. params
. `dirname $0`/simpl/vars

FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS --ansi --height=50% --select-1"

# date=${date:-`date -I`}
start_date=`date_picker --query $date`
start_date=${start_date% *}
end_date=$start_date

fetch_command="`dirname $0`/simpl/fetch_projects"
project_selection=`: | fzf \
	--bind "start:reload:$fetch_command '$project' $start_date $end_date" \
	--bind "change:reload:$fetch_command '{q}' $start_date $end_date" \
	--header 'Select a project to log time on.' --with-nth=1..-2`

project_id=${project_selection#*$separator}
project_name=${project_selection%$separator*}
service_selection=`curl -s -G -H "$auth_key_header" -H "$auth_secret_header" "$base_url""hours/projectservices" \
	-d "q[employee_id]=$employee_id" \
	-d "q[project_id]=$project_id" \
	-d "q[start_date]=$start_date" \
	-d "q[end_date]=$end_date" \
	-d "sort=name" \
	| jq -r ".data[] | .name + \"$separator\" + .id" \
	| fzf --header "Select a service to log time on, for project $project_name." --with-nth=1..-2 \
	${service:+ --query $service}`

service_id=${service_selection#*$separator}
service_name=${service_selection%$separator*}

hours_type_selection=`curl -s -G -H "$auth_key_header" -H "$auth_secret_header" \
	"$base_url""hours/projectservicehourstypes" \
	-d "q[projectservice_id]=$service_id" \
	-d "q[project_id]=$project_id" \
	-d "q[start_date]=$start_date" \
	-d "q[end_date]=$end_date" \
	-d "sort=label" \
	| jq -r ".data[] | .label + \"$separator\" + .id" \
	| fzf --header "Select a hours type for project $project_name service $service_name." \
	${hours_type:+ --query $hours_type} \
	--with-nth=1..-2`

hours_type_id=${hours_type_selection#*$separator}
hours_type_name=${hours_type_selection%$separator*}

start_time=`time_picker 0 0 $start_time`
start_hours=${start_time%:*}
start_minutes=${start_time#*:}
end_time=`time_picker $start_hours $start_minutes $end_time`

hours=`echo $((\`date -j -f '%H:%M:%S' $end_time":00" +%s\` - \`date -j -f '%H:%M:%S' $start_time":00" +%s\`)) / 3600 \
	| bc -l`

agenda_command="agenda_options --date $start_date"

jira_command="jira sprint list --current --show-all-issues --plain --no-headers --columns summary"

if [ ! -z $meeting ]
then
	base_command=$agenda_command
	query=$meeting
else
	base_command=$jira_command
fi

description=`$base_command | fzf \
	--query "$query" \
	--bind "ctrl-a:reload:$jira_command -a \`jira me\`" \
	--bind "ctrl-s:reload:$jira_command -s'To do'" \
	--bind "ctrl-i:reload:$jira_command -s'In Progress'" \
	--bind "ctrl-t:reload:$jira_command -s'Testable'" \
	--bind "ctrl-d:reload:$jira_command -s'Done'" \
	--bind "ctrl-r:reload:$jira_command" \
	--bind "ctrl-g:reload:$agenda_command" \
	--header 'Select a project to log time on.' \
	| awk -F'\t*' '{
		if ($1 ~ /.* to .*/) {
			print $2
		}
		else {
			print $1" : "$2
		}
	}'`

echo "Logging $hours_type_name from $start_time to $end_time on $start_date for $service_name on $project_name."
echo "with description: $description"
echo "for Employee ID: $employee_id"

request_string="{
\"employee_id\":\"$employee_id\",
\"project_id\":\"$project_id\",
\"projectservice_id\":\"$service_id\",
\"type_id\":\"$hours_type_id\",
\"description\":\"$description\",
\"hours\":\"$hours\",
\"start_date\":\"$start_date"T"$start_time":00"\"
}"

curl -H "$auth_key_header" -H "$auth_secret_header" -H 'Content-Type: application/json' "$base_url""hours/hours" \
	-d "$request_string"
