#!/bin/bash

set -e

. params
. `dirname $0`/simpl/vars

FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS --ansi --height=50% --select-1"

# date=${date:-`date -I`}
start_date=`date_picker --query $date`
start_date=${start_date% *}
end_date=$start_date

start_time=`time_picker 0 0 $start_time`
start_hours=${start_time%:*}
start_minutes=${start_time#*:}
end_time=`time_picker $start_hours $start_minutes $end_time`

hours=`echo $((\`date -j -f '%H:%M:%S' $end_time":00" +%s\` - \`date -j -f '%H:%M:%S' $start_time":00" +%s\`)) / 3600 \
	| bc -l`

. `dirname $0`/simpl/fetch_combination

echo "Logging $hours_type_name from $start_time to $end_time on $start_date for $service_name on $project_name."
echo "with description: $description"
echo "for Employee ID: $employee_id"

request_string="{
\"employee_id\":\"$employee_id\",
\"project_id\":\"$project_id\",
\"projectservice_id\":\"$service_id\",
\"type_id\":\"$hours_type_id\",
\"description\":\"$description\",
\"hours\":\"$hours\",
\"start_date\":\"$start_date"T"$start_time":00"\"
}"

curl -H "$auth_key_header" -H "$auth_secret_header" -H 'Content-Type: application/json' "$base_url""hours/hours" \
	-d "$request_string"
