#!/bin/sh

date=$1
if [ -z $date ]
then
	date=`date +'%Y-%m-%d'`
fi
watson log -s --from $date --to $date | awk -F, '{
if (NR > 1 && length > 0) {
	start_cmd = "date -j -f \"%Y-%m-%d %H:%M:%S\" ""\047" $2 "\047" " +%s"
	end_cmd = "date -j -f \"%Y-%m-%d %H:%M:%S\" ""\047" $3 "\047" " +%s"
	start_time=$2
	gsub(" ", "T", start_time)
	if ($4 == "diversen" || $4 ~ /-p.?$/) {
		print "simpl book", $4,"(math \\(("end_cmd")-("start_cmd")\\)/3600)", "-d \047"start_time"\047", "-m", "\x22"$5"\x22"
	}
	else {
		print "simpl book", $4,"(math \\(("end_cmd")-("start_cmd")\\)/3600)", "-d \047"start_time"\047", "-m (issue "$5" | head -n 1)"
	}
}
}' | pbcopy
